### ISSUE TITLE
Inconsistencia en las especies estimadas de Colombia en grupos biológicos

### ISSUE THREAD

**Issue by goreleuro94** [datasketch/sib-colombia#12]
Dentro de los grupos biológicos el número de especies estimadas en Colombia que muestra corresponde al número de especies observadas. El valor de especies estimadas se encuentra en la tabla estimada.

![Issues9](https://github.com/datasketch/sib-colombia/assets/75053168/d80463d0-c150-4e7c-80a2-d71ef521158d)

**Comment by goreleuro94** [comment]
En la ventana de Colombia en los grupos de interés no se esta mostrando el valor de especies estimadas en Colombia.

![imagen](https://github.com/datasketch/sib-colombia/assets/75053168/367fd8e4-47ab-4e1f-839a-ea26e6bf24d5)

**Comment by nleuro-SiB** [comment]
@Angela2201 quería hacerte una aclaración respecto al segundo issue de grupo de interés. Me equivoque y no son especies estimadas, si no observadas. Igual a como se muestra en grupos biológicos. Es decir, el valor de las cifras observadas en Colombia y el texto Especies observadas en Colombia:
![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/4d3fe141-6384-4ccd-9247-546c4a39918f)
