### ISSUE TITLE
Cambios en los ranking

### ISSUE THREAD

**Issue by goreleuro94** [datasketch/sib-colombia#14]
En el home, los textos que acompañan al mapa cambiaron. Ajustamos esta información en la tabla dato_relevante, sin embargo no tenemos claro donde más se debe ajustar para que se vea reflejado en la página
![imagen](https://github.com/datasketch/sib-colombia/assets/75053168/58bed7a5-8ca5-49dd-8558-ad1f52e6517d)

**Comment by jpmarindiaz** [comment]
Estos datos están quemados, en `dato_relavante` están las descripciones completas, pero necesito los texto del ranking tal cuál están en la página para que por fa me los pases actualizados, ustedes me dicen qué hay que cambiar de estos textos:
@goreleuro94 
1. Primer lugar en diversidad de aves, orquídeas y mariposas
2. Segundo en plantas, anfibios, peces dulceacuícolas, reptiles, palmas y murciélagos
3. Quinto en mamíferos

**Comment by goreleuro94** [comment]
Hola @jpmarindiaz estos serian los datos: 
1. Primer lugar en diversidad de aves, orquídeas y mariposas
2. El segundo en variedad de anfibios, peces dulceacuícolas, palmas y murciélagos
3. El sexto en mamíferos.

**Comment by nleuro-SiB** [comment]
En el ranking, falta actualizar el texto inicial:
Colombia es el cuarto país con mayor biodiversidad del mundo. Adicionalmente, en el texto del 2do país sobra la palabra reptiles
![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/e11826ed-ba98-4225-b6d4-66209f1582a3)

**Comment by nleuro-SiB** [comment]
El texto es inconsistente, dice 3 er país sexto en mamíferos. Debería ser: 6to país en mamíferos

![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/9b1d8f67-09c9-4d8a-9b4e-305f03010ad0)

**Comment by Angela2201** [comment]
Se corrige texto en la sección de "6to país en mamíferos"

**Comment by nleuro-SiB** [comment]
Solucionado
