### ISSUE TITLE
No cargan las graficas de top de municipios en los nuevos departamentos

### ISSUE THREAD

**Issue by goreleuro94** [datasketch/sib-colombia#19]
En los nuevos departamentos, en la sección donde se muestran las gráficas comparativas de municipios dentro del departamento se esta cargando una página con error 404, que permite hacer scroll hacía abajo y se ve en footer de la página.
![Issues13](https://github.com/datasketch/sib-colombia/assets/75053168/d19f4ae7-eb08-4cf2-b495-bc524be452bf)

![Issues13-1](https://github.com/datasketch/sib-colombia/assets/75053168/ea0bedd4-18b1-4a41-bb73-cf86876653fa)

**Comment by RicardoOrtizG** [comment]
Issue resuelto: 

<img width="1707" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/651efd7d-17e0-4016-8020-ee7631e43d32">
