### ISSUE TITLE
En los nuevos departamentos no se muestra la gráfica comparativa entre departamento y país

### ISSUE THREAD

**Issue by goreleuro94** [datasketch/sib-colombia#20]
Para los nuevos departamentos no se muestra la gráfica comparativa entre departamento y país. Cargan los textos y la leyenda, pero no la gráfica. 
![imagen](https://github.com/datasketch/sib-colombia/assets/75053168/8cdc5ea3-3719-4818-a519-68b567416c70)

**Comment by RicardoOrtizG** [comment]
Issue resuelto: 

<img width="1636" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/fe96eab4-0b30-4d37-a457-67f7c29ff510">

**Comment by RicardoOrtizG** [comment]
Aún se presenta un error en el resguardo y la reserva. El texto aparece incompleto como se muestra en la imagen: 

<img width="1345" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/0fa1e892-3851-430d-b31f-da2fb4d1746b">

**Comment by RicardoOrtizG** [comment]
Resuelto.
