### ISSUE TITLE
Los porcentajes de publicadores por tipo de organización no coinciden

### ISSUE THREAD

**Issue by goreleuro94** [datasketch/sib-colombia#29]
Realice el calculo del % de aporte por tipo de organización (solo para los organizaciones nacionales) y los % me dan diferente, si se estan redondeando, no es al número próximo más cercano
![imagen](https://github.com/datasketch/sib-colombia/assets/75053168/f2bad8c0-4ac9-439f-83b1-cd7222493892)
![imagen](https://github.com/datasketch/sib-colombia/assets/75053168/d6037f68-6756-4281-b8df-236dc2c7492b)

**Comment by nleuro-SiB** [comment]
En los tooltips que aparecen dentro de la gráfica se debe ajustar el texto. Para el ejemplo de la imagen el texto debería ser: 
_**Tipo de organización: Internacional, cantidad de publicadores: 63 (60%)**_ 
![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/e392ec29-2a3b-404b-98db-bd8e8b1ead0c)



Ya que el texto que se esta mostrando es redundante

**Comment by RicardoOrtizG** [comment]
Resuelto!
