### ISSUE TITLE
Los porcentajes de observaciones aportadas por tipo de organización no coinciden

### ISSUE THREAD

**Issue by goreleuro94** [datasketch/sib-colombia#30]
Realice el calculo del % de aporte por tipo de organización (solo para los organizaciones nacionales) y los % me dan diferente
![imagen](https://github.com/datasketch/sib-colombia/assets/75053168/c1e88460-9566-43f3-8c59-a56bc7950099)
![imagen](https://github.com/datasketch/sib-colombia/assets/75053168/08b7e1c4-7971-4577-8c66-5420cf348df9)

**Comment by nleuro-SiB** [comment]
En los tooltips que aparecen dentro de la gráfica se debe ajustar el texto. Para el ejemplo de la imagen el texto debería ser:
_**Tipo de organización: Centros de investigación, cantidad de observaciones: 93.655 (60%)**_

![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/b081de3f-8bcf-4025-9010-8f0971f7d1f0)

**Comment by RicardoOrtizG** [comment]
Resuelto!
