### ISSUE TITLE
Valor de especie estimada de exóticas inconsistente

### ISSUE THREAD

**Issue by goreleuro94** [datasketch/sib-colombia#32]
El número de especies estimadas para Colombia esta corrido, para exóticas se esta mostrando el de exóticas total y para exóticas con potencial de invasión el de exóticas. 
Había una inconsistencia en la tabla de estimadas en el nombre de la columna especies_exoticas_riesgo_invasion_estimadas que ya se ajustó.
![imagen](https://github.com/datasketch/sib-colombia/assets/75053168/1b569899-22b0-4983-8ba2-e01ec7d25e18)

**Comment by Angela2201** [comment]
Me podrías indicar por favor los valores que deberían ir

**Comment by nleuro-SiB** [comment]
En la tabla de estimadas el campo especies_exoticas_estimadas (1451) para Especies exóticas y especies_exoticas_riesgo_invasion_estimadas (1097) para Exóticas con potencial de invasión con el slug=total.

**Comment by RicardoOrtizG** [comment]
Ajustar colores del gráfico para consistencia: Naranaja: observadas Colombia, Amarillo: Observadas regiones, Gris: Estimadas Colombia.

**Comment by nleuro-SiB** [comment]
Resuelto
