### ISSUE TITLE
Inconsistencia en el número de observaciones y especies en publicadores

### ISSUE THREAD

**Issue by goreleuro94** [datasketch/sib-colombia#36]
Al ingresar a publicadores desde la ventana de Colombia, las cifras para cada publicador no coinciden 

![imagen](https://github.com/datasketch/sib-colombia/assets/75053168/889a075e-bae9-4421-ac84-a01f6403878d)

**Comment by jpmarindiaz** [comment]
Hola, ¿no coinciden contra cuál base?

**Comment by goreleuro94** [comment]
En https://gitlab.com/sib-colombia/cifras-biodiversidad/-/blob/main/db-cifras-sib/region_publicador.tsv tabla region_publicador si buscas ese publicador para colombia el número de registros y especies es diferente al que se ve en la imagen
![imagen](https://github.com/datasketch/sib-colombia/assets/75053168/9efd5d56-4eaf-43cb-9f48-5706d37fa93f)

**Comment by nleuro-SiB** [comment]
El número de especies y registros coincide. Solucionado
![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/a6159784-0233-46f1-a619-f0a88e285f7e)
