### ISSUE TITLE
Inconsistencia barra temáticas en departamentos

### ISSUE THREAD

**Issue by goreleuro94** [datasketch/sib-colombia#37]
Dentro de las temáticas se debe mostrar el valor de la temática para el departamento, el valor para Colombia observada y el de Colombia estimadas. Pero solo se esta mostrando el valor del departamento y el observador para Colombia.
![imagen](https://github.com/datasketch/sib-colombia/assets/75053168/a53e7ae1-ee86-4804-8441-d890ad3739b4)

**Comment by nleuro-SiB** [comment]
Falta presentar el valor de las especies estimadas de Colombia en endémicas

![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/675d9474-10aa-424b-9ebb-9b7667dacbe7)

**Comment by nleuro-SiB** [comment]
Resuelto

**Comment by nleuro-SiB** [comment]
No se están mostrando las estimadas de Colombia en las barras de amenazadas global dentro de las ventanas departamentales:
![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/23f9e0ce-98cc-4607-8c67-269af265391c)

**Comment by jpmarindiaz** [comment]
Hola @nleuro-SiB ¿nos podrías dar más detalles de esto? Con un ejemplo estaría bien. Recuerdo que por diseño en su momento decidimos dejarlo así porque de lo contrario las barras saldrían muy chiquitas si comparamos el 1 de especies observadas CR del amazonas vs el 200.000 de especies estimadas en Colombia. 
Entonces, o ponemos el valor y no se vería nada del número 1 vs 200.000 en las barras, o quitamos el texto indicativo de arriba de las barras Especies estimadas Colombia ()

**Comment by Angela2201** [comment]
Se corrige para que se visualice las especies estimadas en Amenazadas Globales para cada perfil

**Comment by nleuro-SiB** [comment]
Solucionado 

![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/a891fcf5-6cee-44f7-9629-30bff44fe60b)
