### ISSUE TITLE
Falta la lista de especies para las subcategorías de amenazadas

### ISSUE THREAD

**Issue by nleuro-SiB** [datasketch/sib-colombia#42]
No se esta mostrando el icono para observar el top 10 de especies para las subcategorías de amenazadas:

![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/109ca36b-5583-420b-a622-cf3d75e218a0)

**Comment by RicardoOrtizG** [comment]
Ya están los botones que abren la lista del top pero solo para departamento pero el número de especies es inferior a 10 

<img width="1427" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/2b827dc2-3c18-428f-a530-f89cd2dfc0dd">

**Comment by nleuro-SiB** [comment]
Ya se observa el ícono para ver las listas. Solucionado
