### ISSUE TITLE
Inconsistencias en filtros ventana publicadores

### ISSUE THREAD

**Issue by nleuro-SiB** [datasketch/sib-colombia#49]
Al seleccionar un país del publicador diferente a Colombia, el filtro tipo organización sigue estando activo, cuando deberían desactivarse ya que las organizaciones internacionales no tienen esas categorías.

![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/292cd07f-1277-4014-8b5d-58d4c8e378bc)

**Comment by nleuro-SiB** [comment]
No hay forma de filtrar por todas las organizaciones internacionales. Ya que en el campo tipo_organizacion de la tabla publicadores se agrego el valor de Internacional, este se puede agregar en el filtro de esta ventana.

![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/5b4931c0-32f3-4590-8767-c96c18be8949)

**Comment by nleuro-SiB** [comment]
No hay opción para limpiar cada uno de los filtros por aparte, si el usuario quiere eliminar uno de los filtros y mantener los otros, debe usar el botón limpiar filtros y volver a aplicar los filtros que desea mantener.
Por ejemplo, en la imagen se encuentra filtrado por región y país de publicación, pero si quisiera ver de nuevo todos los publicadores quitando el filtro de país publicador hay que limpiar todos los filtros y volver a seleccionar la región:

![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/a82ef504-dfe4-4383-b834-7031dadf2558)

**Comment by RicardoOrtizG** [comment]
- Reorganizar filtos: 
1. Búsqueda de texto
2. Región
3. Tipo de organización
4. País publlicador

Abajo incluir botón de refrescar todos. 

Idea de botón de filtros: 

<img width="824" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/0e5d1e89-b32e-4f75-a761-c35e970e98d2">


Si tipo de organización se escoge todo menos internacional, país publicador debe ser Colombia. En Internacional se muestran los demás países excepto Colombia.

**Comment by RicardoOrtizG** [comment]
Hay una inconsistencia al seleccionar Colombia desde el filtro, no se muestran resultados. Lo mejor sería dejar a Colombia como la opción por defecto por que agrupa todas las organizaciones disponibles y se vería también las gráficas por defecto.

<img width="1369" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/07aadc1a-43dc-4932-aee6-1142ce17b7dd">

**Comment by nleuro-SiB** [comment]
Al seleccionar países diferentes a Colombia deja seleccionar tipos de organización diferentes a internacional:

![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/ebcd0795-4f5a-4792-8df1-4588a21ba048)

![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/b1ae9e71-0c6e-415d-b543-bb62458546cb)

**Comment by Angela2201** [comment]
Resuelto.
