### ISSUE TITLE
Ajustes en mapa de departamentos / municipios

### ISSUE THREAD

**Issue by RicardoOrtizG** [datasketch/sib-colombia#52]
Eliminar espacios blancos al final del mapa, remover referencia de Leaflet y revisar que el mapa se monta sobre la leyenda al hacer zoom. 

<img width="1440" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/1faf7c5e-f4f9-47fe-8101-215bb1b5bdff">

**Comment by nleuro-SiB** [comment]
Resuelto
