### ISSUE TITLE
Explorador | Ajustar los colores de las gráficas para que sean consistentes con las gráficas. 

### ISSUE THREAD

**Issue by RicardoOrtizG** [datasketch/sib-colombia#55]
Ajustar los colores de las gráficas para que se adapten a los colores de las categorías de amenaza y que se venian usando en el resto del sitio.  Esto aplica también para las categorías CITES. 

Ejemplo: Acá el azul no corresponde:
<img width="1225" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/c0090d77-1698-43ff-9333-160423542a95">

**Comment by RicardoOrtizG** [comment]
En la gráfica de barras se muestra un único color.
<img width="1241" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/b31211f0-015f-4a31-996f-b2cb4280fa75">

Por otro lado veo que el amarillo genera muy poco contraste con el texto (blanco) y no se puede leer
<img width="1269" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/ffd654e7-7486-4307-a46a-1f8d100f0ba9">

Se podrían usar estos colores para mejorar lectura (CR, EN, VU): 

![imagen](https://github.com/datasketch/sib-colombia/assets/15789737/1aba7c9f-7807-4641-aa3a-4f009388ad33)

**Comment by jpmarindiaz** [comment]
Agregado
![image](https://github.com/datasketch/sib-colombia/assets/1489570/a527f43b-5785-4e36-b6a8-351b30fd9fae)

**Comment by RicardoOrtizG** [comment]
Solucionado!
