### ISSUE TITLE
Explorador | Incluir miga de pan sobre las búsquedas realizadas. 

### ISSUE THREAD

**Issue by RicardoOrtizG** [datasketch/sib-colombia#56]
Para orientar al usuario sobre lo que está viendo en el explorador se podría usar una miga de pan.

Ejemplo: 

<img width="1138" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/ad2977e3-9404-4555-92f7-3020a13cd38d">

**Comment by jpmarindiaz** [comment]
Agregada
![image](https://github.com/datasketch/sib-colombia/assets/1489570/c115321e-5400-4305-a28c-8c5b216d6007)

**Comment by jpmarindiaz** [comment]
Agregada

**Comment by nleuro-SiB** [comment]
La miga de pan no esta incluyendo las tildes 
![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/a47bab61-5b27-4659-a59e-7745d6c5cfa2)

**Comment by jpmarindiaz** [comment]
Arreglado para las migas de pan con tildes
![image](https://github.com/datasketch/sib-colombia/assets/1489570/5597882f-331b-455b-84de-9a0801ac867b)
![image](https://github.com/datasketch/sib-colombia/assets/1489570/459c7d05-242b-4894-b903-0c29453042a6)
