### ISSUE TITLE
Explorador | Ajuste en leyenda de gráficos

### ISSUE THREAD

**Issue by RicardoOrtizG** [datasketch/sib-colombia#57]
Ajustar la ubicación de la leyenda, tamaño para que mejore su lectura

<img width="907" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/f91fb05e-3bbb-493f-a1e4-8e6062a03b22">

**Comment by nleuro-SiB** [comment]
En el eje _y_ de las gráficas de barras se están mostrando valores decimales que no son lógicos
![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/c7721bc3-2f98-4957-9f33-b3ed8a14ea16)

**Comment by jpmarindiaz** [comment]
Solucionados los labels
![image](https://github.com/datasketch/sib-colombia/assets/1489570/f6d45bc8-95b8-473c-a098-8d1f5c9a8fd5)

Sobre lo decimales en el eje:
Es un tema de la escala, puede que no se vean bien, pero no son incorrectos porque los valores en las gráficas de todas formas con valores enteros. Los decimales salen por defecto y no tenemos opción de ajustarlos por lo pronto. Sugiero dejarlo como otro issue abierto y no mezclarlo con los textos de la leyenda que ya están solucionados.

**Comment by RicardoOrtizG** [comment]
Solucionado!
