### ISSUE TITLE
Explorador | Texto explicativo del explorador. 

### ISSUE THREAD

**Issue by RicardoOrtizG** [datasketch/sib-colombia#58]
Ajustar el texto para que quede permanente y mejor distribuido a lo largo y no en una columna. Dejar el botón solo por si se quiere ocultar la explicación. 

<img width="1719" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/ea57de1b-eacc-49b0-9f4b-38a1d971f9b1">

**Comment by nleuro-SiB** [comment]
El texto ya se encuentra permanente y el botón permite ocultarlo o mostrarlo. Solucionado

![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/a785d3a2-f985-4083-ba1c-0d301049d6f2)
