### ISSUE TITLE
Explorador | Ajustar enlaces a perfiles de GBIF y CBC en visualización tipo tabla

### ISSUE THREAD

**Issue by RicardoOrtizG** [datasketch/sib-colombia#59]
En la tabla del explorador Las columnas url_gbif y url_cbc muestran información correcta pero en el formato incorrecto,  mientras que las columnas GBIF y CBC muestran información incorrecta en el formato correcto. Es decir, no debería aparecer el enlace en la columna url_cbc sino un texto con hipervínculo mientras que en la columna CBC está el hipervínculo incluso cuando no hay datos por lo que apunta a un enlace roto. Si no hay información debería aparecer vacío. 

Ejemplo: Buteo jamaicensis | en CBC redirige a: https://services.datasketch.co/org_sibhumboldt_sibdata_app/

<img width="1695" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/3bfe8feb-d300-4764-b92c-d89459d26b3b">

**Comment by jpmarindiaz** [comment]
Solucionado
![image](https://github.com/datasketch/sib-colombia/assets/1489570/2b5ea71c-a4b8-4396-b610-6a36b45d338a)

**Comment by RicardoOrtizG** [comment]
Solucionado!
