### ISSUE TITLE
Explorador | Región por defecto en el explorador 

### ISSUE THREAD

**Issue by RicardoOrtizG** [datasketch/sib-colombia#61]
Colombia debería ser la región por defecto en el explorador si no se ingresa desde un departamento en específico. De igual forma se recomienda que el filtro de región quede organizado por orden alfabético dando prioridad a Colombia al inicio de las opciones. 

<img width="222" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/641a9f6f-1b1a-4828-b6c1-d015c2ceadd0">

**Comment by nleuro-SiB** [comment]
Solucionado:

![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/9369c0d4-261e-427b-9bf2-b9e294383841)
