### ISSUE TITLE
Visualización de estimadas de San Andrés y Bogotá. 

### ISSUE THREAD

**Issue by RicardoOrtizG** [datasketch/sib-colombia#66]
Debido a que estas dos regiones (San Andrés y Bogotá ) no cuentan con un número de especies estimadas, se recomienda utilizar el template de los municipios para el header de los perfiles para quitar la gráfica. 

Actual
<img width="1370" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/1ba7dc92-24e1-448f-bff0-a0b806f252b1">

Ejemplo: 

<img width="1436" alt="imagen" src="https://github.com/datasketch/sib-colombia/assets/15789737/2845477b-c272-4347-8744-f2303dfdcb96">

**Comment by nleuro-SiB** [comment]
Resuelto
