### ISSUE TITLE
Gráfica de publicadores desaparece

### ISSUE THREAD

**Issue by nleuro-SiB** [datasketch/sib-colombia#79]
Al empezar a aplicar filtros y borrarlos las gráficas de publicadores no se muestran.

Así se ve la ventana apenas carga:
![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/804cbfa6-6d2a-4b2e-b83a-e80d8a537557)

Aplico un filtro:
![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/c988f9fa-5cbf-4258-9e3c-c14e7694e38c)

Y al eliminarlo no se vuelven a mostrar las gráficas:
![imagen](https://github.com/datasketch/sib-colombia/assets/142612871/0920b9ec-83c2-4dd2-88bc-099d038a7ea5)

**Comment by Angela2201** [comment]
Solucionado.
