### ISSUE TITLE
Inconsistencia en Exóticas en ventanas departamentales

### ISSUE THREAD

**Issue by goreleuro94** [datasketch/sib-colombia#9]
En la exóticas totales de Boyacá se está mostrando el listado de especies para la subcategoría exóticas. Adicionalmente, no esta cargando el botón para desplegar la lista de especies en la subcategoría especies exóticas con potencial de invasión

![Issues7](https://github.com/datasketch/sib-colombia/assets/75053168/5bb981e1-8fbd-4aad-8e38-c4996f872036)

**Comment by goreleuro94** [comment]
En la ventana del resguardo se sigue mostrando la lista de especies para la subcategoría de exóticas en donde se debe mostrar la lista total de especies exóticas
![imagen](https://github.com/datasketch/sib-colombia/assets/75053168/37b96a3e-af75-477c-ac63-a44c995839cb)

**Comment by nleuro-SiB** [comment]
Solucionado
